// SPRINT 2

// File generated by FlutterFire CLI. // ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwmBqp-5v6JCgB35Aom8cjT1Hc86DDHdI',
    appId: '1:369286178391:web:93c2d885e98f10b6cb6512',
    messagingSenderId: '369286178391',
    projectId: 'opmobapp',
    authDomain: 'opmobapp.firebaseapp.com',
    storageBucket: 'opmobapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC-shnM_tEMzXHXm8m7c_B6-2rTQFOCso',
    appId: '1:369286178391:android:e850be1f4c1a950bcb6512',
    messagingSenderId: '369286178391',
    projectId: 'opmobapp',
    storageBucket: 'opmobapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfINBMadW4-cea2nPg5316sy8u7hzv9B4',
    appId: '1:369286178391:ios:66d1f88c5018dff6cb6512',
    messagingSenderId: '369286178391',
    projectId: 'opmobapp',
    storageBucket: 'opmobapp.appspot.com',
    iosBundleId: 'com.example.carentalapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwmBqp-5v6JCgB35Aom8cjT1Hc86DDHdI',
    appId: '1:369286178391:web:7a10ee82d0911d13cb6512',
    messagingSenderId: '369286178391',
    projectId: 'opmobapp',
    authDomain: 'opmobapp.firebaseapp.com',
    storageBucket: 'opmobapp.appspot.com',
  );
}
